services:

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=OilerRig'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=oiler'
      - 'POSTGRES_URL=jdbc:postgresql://postgres:5432/OilerRig'
    ports:
      - "5433:5432"

  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_PASS=secret'
      - 'RABBITMQ_USER=oiler'
    ports:
      - '5672'
