name: Test, Upload artifact and Deploy (Eventually)
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17 ]
    name: Run unit tests on Java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - run: mvn -f pom.xml clean compile test
  release:
    runs-on: ubuntu-latest
    needs: test
    name: Build, package and upload .jar artifact
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build and package project
        run: mvn -f pom.xml clean package
      - name: Copy jar to app.jar
        run: cp ./target/backend-0.0.1-SNAPSHOT.jar ./target/app.jar
      - name: Upload Maven build artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: ./target/app.jar